### ISSUE TITLE
#3.3 Slider: multiple. Bug with removing

### ISSUE THREAD

**Issue by scabbiaza** [ivan-kleshnin/cyclejs-examples#4]
Hi!

I think i found the bug, can you recheck? Try this sequence:
1. Update the page and remove first and single element on page
2. Add new element
3. Try to remove this new element >> it will not work
4. Add another element >> now you can remove them both

**Comment by ivan-kleshnin** [comment]
This is that bug with CycleJS https://github.com/staltz/cycle/issues/87
We wait for official fix release to update dependencies.
