### ISSUE TITLE
#3.4 update HTML

### ISSUE THREAD

**Issue by scabbiaza** [ivan-kleshnin/cyclejs-examples#5]
Hello!

I'm sorry if i'm asking silly question.
I don't understand this example: #3.4 Slider: colors

Nothing happens by changing "Amount" input:
http://puu.sh/gKA0h.png
http://puu.sh/gKA27.png

**Comment by ivan-kleshnin** [comment]
This is to represent unrelated properties. When you move slider, input tracks it.
When you change color text value (try to input any valid CSS value...) – div background tracks it.
Color and slider are NOT connected in any way, they are just props of implicit "model".

**Comment by ivan-kleshnin** [comment]
Need to improve HTML: normalize element height etc...

**Comment by ivan-kleshnin** [comment]
No longer relevant.
